[2025-08-01 13:24:53,293] 12 utils.logging - INFO - downloading data from kaggle...
[2025-08-01 13:24:55,552] 16 utils.logging - INFO - saving raw data...
[2025-08-01 13:24:55,700] 20 utils.logging - INFO - splitting into train, test and validation
[2025-08-01 13:24:55,728] 23 utils.logging - INFO - saving train, test and validation
[2025-08-01 13:24:55,876] 20 utils.logging - INFO - Running preprocessing pipeline...
[2025-08-01 13:24:55,876] 80 utils.logging - INFO - Starting preprocessing pipeline...
[2025-08-01 13:24:55,876] 22 utils.logging - INFO - Reading training data for imbalance handling...
[2025-08-01 13:24:55,938] 27 utils.logging - INFO - Handling imbalance using RandomOverSampler...
[2025-08-01 13:24:56,026] 43 utils.logging - INFO - Building preprocessor pipeline...
[2025-08-01 13:24:56,034] 62 utils.logging - INFO - Preprocessor saved at model/preprocessor.pkl
[2025-08-01 13:24:56,034] 92 utils.logging - INFO - Fitting and transforming training data...
[2025-08-01 13:24:56,240] 115 utils.logging - INFO - Saved preprocessed X to data/processed/X_processed.csv
[2025-08-01 13:24:56,240] 116 utils.logging - INFO - Saved target y to data/processed/y.csv
[2025-08-01 13:24:56,240] 23 utils.logging - INFO - Training model ....
[2025-08-01 13:24:56,240] 19 utils.logging - INFO - \U0001f4e5 Loading training data...
[2025-08-01 13:24:56,272] 23 utils.logging - INFO - \U0001f680 Starting MLflow run...
[2025-08-01 13:25:29,487] 46 utils.logging - INFO - \u2705 RandomForestClassifier trained and logged to MLflow.
[2025-08-01 13:25:29,495] 26 utils.logging - INFO - Evaluating the model
[2025-08-01 13:25:29,495] 12 utils.logging - INFO - \U0001f50d Loading validation data...
[2025-08-01 13:25:29,550] 17 utils.logging - INFO - \U0001f4e6 Loading preprocessor and transforming validation data...
[2025-08-01 13:25:29,578] 63 utils.logging - ERROR - \u274c Error occurred during evaluation.
Traceback (most recent call last):
  File "C:\Users\Hp\Desktop\CustomerChurn\src\components\evaluation.py", line 19, in evaluate_model
    X_val_transformed = preprocessor.transform(X_val)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\_set_output.py", line 140, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\compose\_column_transformer.py", line 770, in transform
    check_is_fitted(self)
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py", line 1390, in check_is_fitted
    raise NotFittedError(msg % {"name": type(estimator).__name__})
sklearn.exceptions.NotFittedError: This ColumnTransformer instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.
